### ISSUE TITLE
`composer install` fails with no vendor folder

### ISSUE THREAD

**Issue by johncook** [joachim-n/composer-manifest#1]
When running composer install (with a composer.lock file) either for the first time or after removing the vendor folder, I get the following message:

```
$ composer install
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 223 installs, 0 updates, 0 removals
  - Installing cweagans/composer-patches (1.6.5): Loading from cache
Gathering patches for root package.
Gathering patches for dependencies. This might take a minute.
  - Installing composer/installers (v1.6.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.10.0): Loading from cache
  - Installing composer/semver (1.4.2): Loading from cache
  - Installing drupal-composer/drupal-scaffold (2.5.4): Loading from cache
  - Installing symfony/yaml (v3.4.21): Loading from cache
  - Installing symfony/finder (v3.4.17): Loading from cache
  - Installing drupal/console-extend-plugin (0.9.2): Loading from cache
  - Installing joachim-n/composer-manifest (1.0.1): Loading from cache
Plugin installation failed, rolling back
  - Removing joachim-n/composer-manifest (1.0.1)

  [ErrorException]
  include(./vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory
```

After running `composer remove joachim-n/composer-manifest`, composer runs and then I can run `composer require joachim-n/composer-manifest` again and everything is fine again.

I suspect that composer isn't getting the dependencies in the correct order (`symfony/var-dumper` does appear in the installation log after composer remove).

**Comment by joachim-n** [comment]
>   include(./vendor/symfony/var-dumper/Resources/functions/dump.php): failed to open stream: No such file or directory

That's debug code that I left in accidentally. The latest -dev will has that fixed. I hadn't made a new release as I didn't think it would have any impact, but I'll make one now.

**Comment by Boegie** [comment]
Was just about to enter the same "bug", when I stumbled over this one.

I'm currently using the `master` of this great (thanks for that) project,
`"joachim-n/composer-manifest": "dev-master#29186c8",`, which doesn't have that debug code.

A new release would be greatly appreciated.

--Edit--

Meh, so I prevented creating a double issue, but didn't notice you already made a new release.
Thanks!

**Comment by joachim-n** [comment]
> Meh, so I prevented creating a double issue, but didn't notice you already made a new release.

Haha, no problem!
