### ISSUE TITLE
Support for Drupal 11: update package version requirements

### ISSUE THREAD

**Issue by davids4** [joachim-n/composer-manifest#17]
Problem:

Currently, installing the package with the latest D11.x dev fails with requirements errors:
````
$ composer update -W
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - joachim-n/composer-manifest 1.1.5 requires symfony/yaml ^3.4 || ^4.2 || ^5.4 || ^6.1 -> satisfiable by symfony/yaml[v3.4.0-BETA1, ..., 3.4.x-dev, v4.2.0-BETA1, ..., 4.4.x-dev, v5.4.0-BETA1, ..., 5.4.x-dev, v6.1.0-BETA1, ..., 6.4.x-dev].
    - joachim-n/composer-manifest[1.1.0, ..., 1.1.4] require symfony/yaml ^3.4 || ^4.2 -> satisfiable by symfony/yaml[v3.4.0-BETA1, ..., 3.4.x-dev, v4.2.0-BETA1, ..., 4.4.x-dev].
    - You can only install one version of a package, so only one of these can be installed: symfony/yaml[2.0.5, ..., 2.8.x-dev, v3.0.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev, v5.0.0-BETA1, ..., 5.4.x-dev, v6.0.0-BETA1, ..., 6.4.x-dev, v7.1.0-BETA1, ..., 7.2.x-dev].
    - drupal/core-recommended 11.x-dev requires symfony/yaml ~v7.1.1 -> satisfiable by symfony/yaml[v7.1.1, 7.1.x-dev].
    - symfony/yaml[v4.0.10, ..., v4.4.8] require php ^7.1.3 -> your php version (8.3.8) does not satisfy that requirement.
    - Root composer.json requires drupal/core-recommended ^11.x-dev@dev -> satisfiable by drupal/core-recommended[11.x-dev].
    - Root composer.json requires joachim-n/composer-manifest ^1.1 -> satisfiable by joachim-n/composer-manifest[1.1.0, ..., 1.1.5].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
````

Maybe `composer-manifest` version requirements should be bumped a bit so they could be compatible with more recent versions of Drupal, in particular, Drupal `11.x`.

**Comment by joachim-n** [comment]
Thanks for reporting!

Fixed and new release made.

**Comment by davids4** [comment]
Thanks a lot Joachim!

I've just given it a quick try and it seems to be working fine now  with `"drupal/core-recommended": "^11.x-dev@dev"`

One thing though, not sure if the `"symfony/var-dumper": "^4.2"` could cause any issue, or problems with the requirements with D11 core dev....
https://github.com/joachim-n/composer-manifest/blob/master/composer.json#L16C10-L16C28

I haven't had any issue adding the project locally, with `"drupal/core-dev": "^11.x-dev@dev"`, but that's maybe because I have other packages installed as well ... 
Just not sure, but wanted to double check with you.

Thanks again for your great help and reactivity Joachim!

**Comment by joachim-n** [comment]
symfony/var-dumper is only a -dev requirement, it'll only get installed when this library is installed as a root project for development.
