### ISSUE TITLE
dev version flip-flops between formats

### ISSUE THREAD

**Issue by joachim-n** [joachim-n/composer-manifest#18]
Just seen this in a diff:

```
-    drupal/components: '3.x-dev:c953d12ed1dbe66cc21c9a3e4028902e99653d17'
+    drupal/components: 'dev-3.x:c953d12ed1dbe66cc21c9a3e4028902e99653d17`
```

I was doing `composer update --lock` to resolve a merge conflict, and the drupal/components package was not changed by this operation!

**Comment by loopy3025** [comment]
This is a great tool and we love it. However, we've had to pin to "joachim-n/composer-manifest": "dev-master#9353b37dfe02489938e4e655e1e8b743db8f40d3" in order to avoid this flipflopping during ci builds.

**Comment by joachim-n** [comment]
Thanks for the debugging (and great to hear it's useful!)

However, '9353b37dfe02489938e4e655e1e8b743db8f40d3' doesn't seem to be a commit in this repo.

**Comment by loopy3025** [comment]
Fascinating:

https://github.com/joachim-n/composer-manifest/commit/9353b37dfe02489938e4e655e1e8b743db8f40d3

**Comment by loopy3025** [comment]
OH now I remember. It's from this person's PR:

https://github.com/joachim-n/composer-manifest/pull/15

Haha. I forgot all about doing this on a different project months ago.
