### ISSUE TITLE
doesn't record packages that on a dev branch

### ISSUE THREAD

**Issue by joachim-n** [joachim-n/composer-manifest#2]
E.g. in composer.json

`"drupal/recaptcha": "2.x-dev#790211e39e3882139dc93160e6ab14846c2195e9",`

in composer-manifest.yml:

`drupal/recaptcha: dev-2.x`

**Comment by joelpittet** [comment]
Maybe you fixed this already?  I'm seeing `drupal/masquerade: 'dev-2.x:2011b21b3ed75f6faf4fa805de08c46fae155c20'` for example, but I guess I'm not explicit in my `composer.json`?

**Comment by joachim-n** [comment]
Yup, looks like I fixed this in commit 094604c55baa0000193fe73e34e402d2348221f1.
