### ISSUE TITLE
Symfony 5.X Compatibility

### ISSUE THREAD

**Issue by FabienPapet** [joachim-n/composer-manifest#9]
I tried to install it on a Symfony 5.1, but your composer.lock fixes symfony versions 3 / 4 only

```
composer require joachim-n/composer-manifest


  Problem 1
    - joachim-n/composer-manifest[1.1.0, ..., 1.1.2] require symfony/yaml ^3.4 || ^4.2 -> found symfony/yaml[v3.4.0, ..., v3.4.46, v4.2.0, ..., v4.4.16] but it conflicts with your root composer.json require (5.1.*).
    - Root composer.json requires joachim-n/composer-manifest ^1.1 -> satisfiable by joachim-n/composer-manifest[1.1.0, 1.1.1, 1.1.2].

```

**Comment by joachim-n** [comment]
Do you know if it's compatible with Symfony 5? Would you be able to try it and report back?

**Comment by FabienPapet** [comment]
That should be compatible but I can't test right now

See the changelog for symfony/yaml https://github.com/symfony/yaml/blob/5.x/CHANGELOG.md
